### ISSUE TITLE
Game speed changes when a keyboard key is held

### ISSUE THREAD

**Issue by bakesi** [scanlime/robot-odyssey-rewired#13]
When I press and hold any keyboard key the game speed changes.
E.g., robots start moving faster.

This behaviour may be reproduced in all modern browsers on Windows, not sure about other OS-es

**Comment by bakesi** [comment]
This seems to be related to init () method in buttons.js. I think the repeat delay or/and rate should be added to a keyboard button pressed as well

**Comment by scanlime** [comment]
this is an intentional feature, the game runs faster when the keyboard
queue is backed up.

**Comment by bakesi** [comment]
Yeah, makes sense now that I think of it

**Comment by scanlime** [comment]
Ok! If you'd like to experiment with the behavior, here's a link to the code responsible (now that I'm on a laptop):

https://github.com/scanlime/robot-odyssey-rewired/blob/31690f58977a549adc13ccf2665558385006f4de/src/engine/engine.cpp#L69

Cheers!
