### ISSUE TITLE
Original source?

### ISSUE THREAD

**Issue by clort81** [scanlime/robot-odyssey-rewired#26]
Original was written in a high level language i assume - is that source available?
I see OOP concepts all over and it would be very interesting to see how it was done back in the day on apple/ibm.  Lots of loadable objects on disk?

**Comment by cromerc** [comment]
No, the original source isn't public. This is a remake, the code here is not related to the original at all.

**Comment by scanlime** [comment]
The original game was written in assembly, you can tell it isn't code a compiler would produce. There are reverse engineering notes in this repo but no source code. The "rewired" port works by disassembling and patching and translating the original machine code.
